modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"

[[mods]]
modId="bonk"
version="1.0.0"
displayName="Bonk"
credits="MCreator for helping to make the mod"
displayURL="https://github.com/WiseDragoon5374/bonk"
logoFile="logo.png"
authors="North_G (WiseDragoon5374)"
description='''
Adds way too many dumb features and blocks.
'''

[[dependencies.bonk]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




